import { AppShell, Group, Anchor, Button, Container, Text, Divider, Menu } from '@mantine/core';
import { Link, Outlet, useNavigate } from 'react-router-dom';
import { IconBrandGithub, IconBrandLinkedin } from '@tabler/icons-react';
// Global reactive state hooks
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext'; 

export function Layout() {
  const { isAuthenticated, isAdmin, logout } = useAuth();
    const { cartCount } = useCart(); // Destructure live reactive counter state
  const navigate = useNavigate(); // INITIALIZE NAVIGATOR

  // Explicit interceptor ensures security states wipe before route context switches
  const handleLogoutClick = () => {
    logout();
    navigate('/');
  };


  return (
    <AppShell
      header={{ height: 60 }}
      padding="md"
      styles={{
        main: { background: 'var(--mantine-color-dark-8)', minHeight: '100vh', display: 'flex', flexDirection: 'column' }
      }}
    >

      {/* HEADER SECTION */}
      <AppShell.Header px="md">
        <Container size="lg" h="100%">
          <Group justify="space-between" align="center" h="100%" wrap="nowrap">            
            
            {/* BRAND LOGO LANE - Pinned Left */}
            <Anchor component={Link} to="/" style={{ display: 'flex', alignItems: 'center', flexShrink: 0 }}>
              <img 
                src="/images/logo.png" 
                alt="Decibels Logo" 
                style={{ 
                  height: '36px', // Slightly tightened for mobile optimization             
                  width: 'auto',              
                  display: 'block',
                  filter: 'invert(1) brightness(1.5)', 
                  transition: 'transform 0.2s ease'       
                }} 
                onMouseEnter={(e) => e.currentTarget.style.transform = 'scale(1.02)'}
                onMouseLeave={(e) => e.currentTarget.style.transform = 'scale(1)'}
              />
            </Anchor>

{/* MIDDLE NAVIGATION LINKS */}
<Group gap="md" justify="center" style={{ flex: 1, minWidth: 0, flexWrap: 'nowrap' }}>
  {/* ADMIN VIEW */}
  {isAuthenticated && isAdmin && (
    <Menu shadow="md" width={180} openDelay={50} closeDelay={100}>
      <Menu.Target>
        <Anchor c="dimmed" size="sm" style={{ cursor: 'pointer', display: 'flex', alignItems: 'center', userSelect: 'none', whiteSpace: 'nowrap' }}>
          Manage ▼
        </Anchor>
      </Menu.Target>
      <Menu.Dropdown bg="var(--mantine-color-dark-7)" style={{ border: '1px solid var(--mantine-color-dark-4)' }}>
        <Menu.Item component={Link} to="/admin/orders" c="var(--mantine-color-dark-0)">Orders</Menu.Item>
        <Menu.Item component={Link} to="/admin/products" c="var(--mantine-color-dark-0)">Products</Menu.Item>
      </Menu.Dropdown>
    </Menu>
  )}

  {/* STANDARD CUSTOMER VIEW */}
  {isAuthenticated && !isAdmin && (
    <Anchor component={Link} to="/orders" c="dimmed" size="sm" style={{ whiteSpace: 'nowrap' }}>
      <Text component="span" visibleFrom="xs">My Orders</Text>
      <Text component="span" hiddenFrom="xs">Orders</Text>
    </Anchor>
  )}

  {isAuthenticated && (
    <Anchor component={Link} to="/cart" c="dimmed" size="sm" style={{ whiteSpace: 'nowrap' }}>
      Cart ({cartCount})
    </Anchor>
  )}
</Group>

            {/* IDENTITY ACTIONS LANE - Pinned Right, Never shrinks or wraps out */}
            <Group gap="sm" justify="flex-end" style={{ flexShrink: 0 }}>
              {isAuthenticated ? (
                <Button variant="light" color="red" size="xs" onClick={handleLogoutClick}>Logout</Button>
              ) : (
                <Button component={Link} to="/login" variant="light" size="xs">Login</Button>
              )}
            </Group>

          </Group>
        </Container>
      </AppShell.Header>

      {/* CORE VIEWPORT LAYER */}
      <AppShell.Main style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
        <Container 
          size="lg" 
          py="xl" 
          style={{ 
            flex: 1, 
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
            minWidth: 0
          }}
        >
          {/* ISOLATED WRAPPER BOX: 
            This div explicitly catches overflowing tables or data grids generated by child components,
            safeguarding the screen edges and enabling smooth momentum horizontal swipe-scrolling on all mobile browsers.
          */}
          <div 
            style={{ 
              width: '100%', 
              overflowX: 'auto', 
              WebkitOverflowScrolling: 'touch' 
            }}
          >
            {/* Outlet is the dynamic zone where nested child route pages render */}
            <Outlet />
          </div>
        </Container>

       {/* PERSISTENT FOOTER */}
        <Container size="lg" w="100%" mt="auto" pt="xl" pb="md">
          <Divider my="sm" color="gray.8" />
          <Group justify="space-between" wrap="nowrap">
            
            {/* Left Spacer - Kept visible everywhere to anchor true horizontal centering */}
            <Group style={{ flex: 1 }} justify="flex-start">
              <Text size="xs" style={{ visibility: 'hidden', width: '56px' }}>Spacer</Text>
            </Group>
            
            {/* Middle Text Element - Dead Center */}
            <Text size="xs" c="dimmed" ta="center" style={{ flex: 1, whiteSpace: 'nowrap' }}>
              © {new Date().getFullYear()} Decibels
            </Text>
            
            {/* Right Social Icons */}
            <Group gap="md" wrap="nowrap" justify="flex-end" style={{ flex: 1 }}>
              <Anchor 
                href="https://github.com/gritNgo/Decibels" 
                target="_blank" 
                rel="noopener noreferrer" 
                c="dimmed"
                style={{ display: 'flex', alignItems: 'center', transition: 'color 0.2s ease' }}
                onMouseEnter={(e) => e.currentTarget.style.color = 'var(--mantine-color-blue-4)'}
                onMouseLeave={(e) => e.currentTarget.style.color = ''}
              >
                <IconBrandGithub size={20} stroke={1.5} />
              </Anchor>

              <Anchor 
                href="https://www.linkedin.com/in/fiorenso-wattalage-fernando/" 
                target="_blank" 
                rel="noopener noreferrer" 
                c="dimmed"
                style={{ display: 'flex', alignItems: 'center', transition: 'color 0.2s ease' }}
                onMouseEnter={(e) => e.currentTarget.style.color = 'var(--mantine-color-blue-4)'}
                onMouseLeave={(e) => e.currentTarget.style.color = ''}
              >
                <IconBrandLinkedin size={20} stroke={1.5} />
              </Anchor>
            </Group>

          </Group>
        </Container>
      </AppShell.Main>
    </AppShell>
  );
}